#!/bin/bash

docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sde -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=0 --ip=192.168.178.230 --network=macvlan0 --name ceph_osd_sde ceph/daemon osd
docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sdf -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=1 --ip=192.168.178.231 --network=macvlan0 --name ceph_osd_sdf ceph/daemon osd
docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sdh -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=2 --ip=192.168.178.232 --network=macvlan0 --name ceph_osd_sdh ceph/daemon osd
docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sdi -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=3 --ip=192.168.178.233 --network=macvlan0 --name ceph_osd_sdi ceph/daemon osd
docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sdj -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=4 --ip=192.168.178.234 --network=macvlan0 --name ceph_osd_sdj ceph/daemon osd
docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sdk1 -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=5 --ip=192.168.178.235 --network=macvlan0 --name ceph_osd_sdk1 ceph/daemon osd
docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sdk2 -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=6 --ip=192.168.178.236 --network=macvlan0 --name ceph_osd_sdk2 ceph/daemon osd
docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sdl -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=7 --ip=192.168.178.237 --network=macvlan0 --name ceph_osd_sdl ceph/daemon osd
docker run -d --privileged=true --pid=host -v /docker/ceph/data/etc:/etc/ceph -v /docker/ceph/data/lib:/var/lib/ceph/ -v /dev/:/dev/ -v /run/udev/:/run/udev/ -e OSD_DEVICE=/dev/sdm -e OSD_TYPE=disk -e OSD_BLUESTORE=1 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE -e OSD_ID=8 --ip=192.168.178.238 --network=macvlan0 --name ceph_osd_sdm ceph/daemon osd

exit 0
