#!/bin/sh



docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.230 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sde --no-systemd
docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.231 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sdf --no-systemd
docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.232 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sdh --no-systemd
docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.233 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sdi --no-systemd
docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.234 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sdj --no-systemd
docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.235 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sdk1 --no-systemd
docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.236 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sdk2 --no-systemd
docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.237 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sdl --no-systemd
docker run --rm --privileged=true -v /docker/ceph/data/lib:/var/lib/ceph/ -v /var/log/ceph:/var/log/ceph/ -v /docker/ceph/data/etc:/etc/ceph -v /dev/:/dev/ -v /run/lock/lvm:/run/lock/lvm:z -v /run/lvm/:/run/lvm/ -v /var/run/udev/:/var/run/udev/:z --ip=192.168.178.238 --network=macvlan0 --entrypoint ceph-volume ceph/daemon lvm prepare --bluestore --data /dev/sdm --no-systemd

exit 0
